# Generated by Django 4.1.3 on 2022-12-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nome:")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Sobrenome"),
                ),
                ("car_id", models.IntegerField(verbose_name="Id Carro:")),
                (
                    "customer_need",
                    models.CharField(
                        max_length=100, verbose_name="Necessidade do cliente:"
                    ),
                ),
                (
                    "car_title",
                    models.CharField(max_length=100, verbose_name="Nome do carro:"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade:")),
                ("state", models.CharField(max_length=100, verbose_name="Estado:")),
                ("email", models.CharField(max_length=100, verbose_name="Email:")),
                ("phone", models.CharField(max_length=100, verbose_name="Telefone:")),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="Mensagem:"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, verbose_name="Id Usuário:"),
                ),
                (
                    "create_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
