# Generated by Django 4.1.3 on 2022-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Sobrenome"),
                ),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="Função"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Foto"
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(max_length=100, verbose_name="Facebook"),
                ),
                (
                    "twitter_link",
                    models.URLField(max_length=100, verbose_name="Twitter"),
                ),
                (
                    "google_plus_link",
                    models.URLField(max_length=100, verbose_name="Google"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
        ),
    ]
