# Generated by Django 4.1.3 on 2022-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_team_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.ImageField(default=True, upload_to="images/% Y/% m/% d/"),
        ),
    ]
