# Generated by Django 4.1.3 on 2022-11-23 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Descrição"),
        ),
    ]
