# Generated by Django 4.1.3 on 2022-11-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                max_length=100,
                verbose_name="Portas",
            ),
        ),
    ]
